function(lf_enable_compiler_warnings target)
    if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        if(${CMAKE_C_COMPILER} MATCHES "gcc\\.exe")
            target_compile_options(${target} PRIVATE -Wall)
        else()
            target_compile_options(${target} PRIVATE /W4)
        endif()
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
        target_compile_options(${target} PRIVATE -Wall)
    else()
        target_compile_options(${target} PRIVATE -Wall)
    endif()
endfunction()