function(lf_enable_compiler_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
    elseif(APPLE)
        target_compile_options(${target} PRIVATE -Wall)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
    endif()
endfunction()