#ifndef LF_SOCKET_SUPPORT_H
#define LF_SOCKET_SUPPORT_H

#define NUM_SOCKET_RETRIES 10

#define DELAY_BETWEEN_SOCKET_RETRIES MSEC(100)

typedef enum {
  HEADER_READ,
  READ_MSG_TYPE_FED_IDS,
  READ_MSG_TYPE_NEIGHBOR_STRUCTURE,
  READ_MSG_TYPE_TAGGED_MESSAGE,
  KEEP_READING,
  FINISH_READ
} read_state_t;

#endif // LF_SOCKET_SUPPORT_H
