name: Unit tests

on:
  workflow_call:
    inputs:
      cmake-args:
        description: Arguments to pass to cmake
        type: string
        required: false
jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out reactor-c repository
        uses: actions/checkout@v2

      - name: Build and run unit tests ${{ inputs.cmake-args }}
        run: |
          mkdir build
          cd build
          cmake .. ${{ inputs.cmake-args }}
          cmake --build .
          sudo make test
      - name: Run RTI unit tests
        run: |
          cd core/federated/RTI
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest
          
