name: Unit tests

on:
  workflow_call:
    inputs:
      cmake-args:
        description: Arguments to pass to cmake
        type: string
        required: false
jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out reactor-c repository
        uses: actions/checkout@v2

      - name: Build and run unit tests ${{ inputs.cmake-args }}
        run: |
          mkdir build
          cd build
          cmake .. ${{ inputs.cmake-args }}
          cmake --build .
          make test
